jobs:
- job: Default
  timeoutInMinutes: 90
  pool:
    vmImage: Ubuntu-16.04
  variables:
    CC: gcc-7
    CXX: g++-7
  steps:
  
  - script: |
      nproc
      lscpu
    displayName: 'Machine info'
  
  - script: |
      sudo chown -R $USER $CONDA
      . $CONDA/etc/profile.d/conda.sh
      conda create --yes --quiet --name debug python=3.7.3 pip
    displayName: 'Setup conda'
  
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate debug
      conda install -y -q numpy scipy mkl openblas theano
      theano-cache purge
      pip install -U pip
      pip install -U setuptools
    displayName: 'Install dependencies'
  
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate debug
      gcc --version
      STARRY_DEBUG=1 pip install starry@git+https://github.com/rodluger/starry@master
      pip install healpy
    displayName: 'Install starry'
  
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate debug
      python debug.py
    displayName: 'Run the test'