name: Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pymc-version: "pymc3==3.9.3"
            starry-version: "starry@git+https://github.com/rodluger/starry@master"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.pymc-version }}-

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry_process
          environment-file: environment.yml

      - name: Set up environment
        shell: bash -l {0}
        run: |
          jupyter nbextension enable --py widgetsnbextension
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip uninstall -y theano  # so that we know which version we're getting
          python -m pip install ${{ matrix.pymc-version }} ${{ matrix.starry-version }}
          python -m pip install -e ".[app,tests]"
          python -c 'import theano; print(theano.__version__)'

      - name: Docs
        shell: bash -l {0}
        run: |
          make -C docs html

      - name: Push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd docs/_build/html
          git init
          touch .nojekyll
          git add .nojekyll
          git add -f *
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "building the docs"
          git push -q -f https://github.com/$GITHUB_REPOSITORY gh-pages
