name: Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: JOSS paper draft

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry_process
          environment-file: environment.yml
          auto-activate-base: false
      - name: Install
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install .
      - name: Get theano compiledir
        id: compiledir
        shell: bash -l {0}
        run: |
          python -c "import theano; print('::set-output name=compiledir::' + theano.config.compiledir.split('/')[-1])"
      - name: "Cache ~/.theano"
        uses: actions/cache@v2
        with:
          path: ~/.theano
          key: joss-${{ steps.compiledir.outputs.compiledir }}
          restore-keys: |
            joss-
      - name: Docs
        shell: bash -l {0}
        run: |
          make -C docs html
      - name: Push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd docs/_build/html
          git init
          touch .nojekyll
          git add .nojekyll
          git add -f *
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "building the docs"
          git push -q -f https://github.com/$GITHUB_REPOSITORY gh-pages
