name: examples
on:
  push:
    branches:
      - main
  pull_request:
    branches:
  #release:
  #  types:
  #    - published

jobs:
  notebooks:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pymc-version: "pymc3==3.9.3"
            starry-version: "starry@git+https://github.com/rodluger/starry@master"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.pymc-version }}-

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry_process
          environment-file: environment.yml

      - name: Set up environment
        shell: bash -l {0}
        run: |
          jupyter nbextension enable --py widgetsnbextension
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip uninstall -y theano  # so that we know which version we're getting
          python -m pip install ${{ matrix.pymc-version }} ${{ matrix.starry-version }}
          python -m pip install -e ".[docs]"
          python -c 'import theano; print(theano.__version__)'

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          jupyter nbconvert --to notebook --execute docs/notebooks/*.ipynb

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/notebooks

      - name: Generate plots for README
        shell: bash -l {0}
        run: |
          python docs/generate_readme_plots.py
          mkdir readme-figures
          mv samples_*.png readme-figures/

      - uses: actions/upload-artifact@v2
        with:
          name: readme-figures-for-${{ github.sha }}
          path: readme-figures

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1.0.0
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
