name: JOSS
on:
  push:
    branches: [master, joss]
  pull_request:
    branches: [master]
jobs:
  paper:
    runs-on: ubuntu-latest
    name: JOSS paper draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry_process
          environment-file: environment.yml
          auto-activate-base: false
      - name: Install
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install "pymc3==3.9.3" "theano==1.0.5"
          python -m pip install .
      - name: Get theano compiledir
        id: compiledir
        shell: bash -l {0}
        run: |
          python -c "import theano; print('::set-output name=compiledir::' + theano.config.compiledir.split('/')[-1])"
      - name: "Cache ~/.theano"
        uses: actions/cache@v2
        with:
          path: ~/.theano
          key: tutorials-${{ steps.compiledir.outputs.compiledir }}
          restore-keys: |
            tutorials-${{ steps.compiledir.outputs.compiledir }}
            tutorials-
      - name: Figures
        shell: bash -l {0}
        run: |
          cd joss/figures
          ls *.py | xargs -n 1 python
      - name: PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md
      - name: Push
        run: |
          git checkout --orphan joss-paper
          git rm --cached -rf .
          git add -f joss
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "building JOSS paper"
          git push -q -f https://github.com/$GITHUB_REPOSITORY joss-paper
