name: JOSS
on:
  push:
    branches: [master, joss]
  pull_request:
    branches: [master]
jobs:
  paper:
    runs-on: ubuntu-latest
    name: JOSS paper draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install .
          python -m pip install -U ipython
      - name: Figures
        run: ls joss/figures/*.py | xargs -n 1 python
      - name: PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md
      - name: Push
        run: |
          git checkout --orphan joss-paper
          git rm --cached -rf .
          git add -f joss
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "building JOSS paper"
          git push -q -f https://github.com/$GITHUB_REPOSITORY joss-paper
